### ISSUE TITLE
Битые ссылки

### ISSUE THREAD

**Issue by MichaelMonashev** [catalyst-team/classification#14]
Тут половина ссылок на примеры неправильные: https://catalyst-team.github.io/catalyst/info/examples.html

**Comment by TezRomacH** [comment]
Должно исправится в [#303](https://github.com/catalyst-team/catalyst/pull/303). Спасибо!

**Comment by MichaelMonashev** [comment]
Нифига не исправилось. Нажал первую ссылку: https://github.com/catalyst-team/catalyst/blob/master/examples/notebook-example.ipynb получил 404 .

**Comment by TezRomacH** [comment]
ПР пока еще не замержен, но та страница будет полностью эквивалентна этой -- https://github.com/catalyst-team/catalyst/tree/master/examples

По ссылкам можно тут побегать

**Comment by TezRomacH** [comment]
Доку обновили, теперь все работает. Еще раз спасибо!
